var yackLocal =
{
    you: " you ",
    MiniStream: "Mini Stream",
    App_4: "blog",
    App_5: "status",
    App_7: "photo",
    App_8: "photo album",
    App_23: "note",
    App_25: "link",
    App_29: "photo",
    App_33: "recognition",
    App_46: "feedback",
    App_52: "feedback",
    App_53: "feedback",
    App_55: "mood",
    App_56: "document",
    App_57: "folder",
    App_58: "file",
    App_59: "media",
    App_62: "file",
    App_63: "file",
    App_64: "file",
    item: "item",
    comment: "comment",
    Action_10: " commented on ",
    Action_11: " commented on ",
    Action_16: " Likes ",
    Action_19: " tagged ",
    Action_21: " tagged a comment ",
    Action_22: " tagged a link ",
    Action_23: " tagged ",
    hasTaggedTopic: " tagged a topic ",
    commentedAfterYou: " commented after you ",
    changedTheme: " has changed current Yackstar Theme.",
    createdNewSpace: " has created a new space ",
    changedProfilePicture: " has changed his profile picture.",
    joinedSpace: " has joined ",
    leftSpace: " has left ",
    editTopicDescription: " has edited the description of Topic ",
    addedTopicExperience: " has added work experience to Topic ",
    respondedToFeedbackRequest: " has responded to ",
    your: "your",
    his: "their",
    inside: "inside",
    withTopic: "with ",
    on: "on ",
    Page: "page ",
    noRecentActivities: "No recent activity to display.",
    noAuth:"You need to go to the Yackstar Stream Authentication page in the WordPress Admin (under settings) before your activity can be shown.",
    serverError:"There was a problem with processing your request."
};